apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-frontend.fullname" . }}
  labels:
    {{- include "app-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app-frontend.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{- include "app-frontend.labels" . | nindent 12 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4200