# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-db.fullname" . }}
type: Opaque
data:
  mongodb-root-password: {{ .Values.mongodbRootPassword }}
  mongodb-password: {{ .Values.mongodbPassword }}
