# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ include "app-db.name" . }}
spec:
  selector:
    app: {{ include "app-db.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 27017
  type: {{ .Values.service.type }}
